version: '3'

networks:
  neo4j:
volumes:
  neo4j:

services:
  nginx:
    image: "nginx:alpine"
    restart: on-failure
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app
    restart: on-failure
    ports:
     - "5000:80"
  redis:
    image: "redis:alpine"
    restart: on-failure
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app
    restart: on-failure
    ports:
      - "3000:3000"
  neo4j:
    image: "neo4j:latest"
    networks:
      - neo4j
    environment:
      - NEO4J_AUTH=neo4j/Gamers
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_connector_bolt_advertised__address=:7687
    ports:
      - "7474:7474"
      - "6477:6477"
      - "7687:7687"
    volumes:
      - ./data/neo4j:/data
    restart: on-failure